# Generated by Django 4.2.7 on 2026-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_verified_emailverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('student', 'Öğrenci'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
