# Generated by Django 4.2.7 on 2026-05-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Mentonnect', max_length=100)),
                ('site_description', models.TextField(default="Türkiye'nin önde gelen mentorluk platformu")),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('registration_open', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
